### ISSUE TITLE
ParagonServiceProvider is not found

### ISSUE THREAD

**Issue by dwjordan** [kirschbaum-development/paragon#16]
When testing with a fresh Laravel install, with `composer require kirschbaum-development/paragon` we get this:

![SCR-20241021-tl1](https://github.com/user-attachments/assets/dd3078b9-918c-4301-b949-dd37058542f9)

It may have something to do with the autoload settings in `composer.json`

**Comment by brandonferens** [comment]
Fixed in commit 5c67b20
